export const courses = [
  {
    id: 1,
    title: 'Guitar Beginner',
    instrument: 'Guitar',
    description: 'Master the fundamentals of guitar, including chords, strumming patterns, and basic music theory.',
    level: 'Beginner',
    duration: '12-16 Weeks',
  },
  {
    id: 2,
    title: 'Guitar Advanced',
    instrument: 'Guitar',
    description: 'Elevate your playing with complex solos, advanced theory, and diverse musical styles.',
    level: 'Advanced',
    duration: '16-32 Weeks',
  },
  {
    id: 3,
    title: 'Vocals',
    instrument: 'Voice',
    description: 'Discover your unique voice through vocal exercises, pitch control, and performance techniques.',
    level: 'All Levels',
    duration: '12-16 Weeks',
  },
  {
    id: 4,
    title: 'Piano',
    instrument: 'Piano',
    description: 'Develop technical proficiency and musicality on the piano, from classical to contemporary pieces.',
    level: 'Beginner to Intermediate',
    duration: '12-16 Weeks',
  },
  {
    id: 5,
    title: 'Ukulele',
    instrument: 'Ukulele',
    description: 'Learn to play this cheerful instrument with easy chords and fun, rhythmic strumming.',
    level: 'Beginner',
    duration: '12-16 Weeks',
  },
  {
    id: 6,
    title: 'Flute',
    instrument: 'Flute',
    description: 'Master breath control, finger technique, and beautiful melodies on the flute.',
    level: 'Beginner',
    duration: '9-12 Weeks',
  },
];

export const faculty = [
  {
    id: 1,
    name: 'Dr. Evelyn Reed',
    expertise: 'Head of Piano Studies',
  },
  {
    id: 2,
    name: 'Marcus Holloway',
    expertise: 'Guitar & Modern Music',
  },
  {
    id: 3,
    name: 'Clara Schumann',
    expertise: 'Violin & Orchestral Studies',
  },
  {
    id: 4,
    name: 'Leo Vance',
    expertise: 'Vocal & Performance Coach',
  },
];

export const testimonials = [
  {
    id: 1,
    name: 'Charak srivastava',
    course: 'Music Student',
    quote: "This academy of music has given me a lots of knowledge about music. The music teachers are very good at assessing student's abilities and interests and adjusting their lessons accordingly. They are gifted musicians but also highly skilled at teaching. I highly recommend everyone to join TCAM.",
    rating: 5,
  },
  {
    id: 2,
    name: 'Shivesh Pratap Singh',
    course: 'Vocal Training',
    quote: "Vocal coach “Rohan sir” is teacher cum buddy! We laugh learn and apply the learnings in Mic setup day. Best part is you can sing 2 songs after 10 days of practice which is very essential in your singing journey. I recommend this vocal classes. You can 1st take free trial class. I am sure you will learn a lot about basics. All the best singers 🎤 🎙️",
    rating: 4,
  },
  {
    id: 3,
    name: 'Rohan Kapoor',
    course: 'Guitar Student',
    quote: "Amazing experience! The curriculum is very well structured. Whether you are a beginner or looking to advance your skills, this is the place to be.",
    rating: 5,
  },
  {
    id: 4,
    name: 'Meera Das',
    course: 'Piano Learner',
    quote: "The atmosphere at The Chromatica Academy is so inspiring. I look forward to my piano classes every week. Highly recommended!",
    rating: 5,
  },
  {
    id: 5,
    name: 'Siddharth Singh',
    course: 'Music Enthusiast',
    quote: "Very professional and disciplined environment. The focus on technique and theory along with practical playing is what makes them stand out.",
    rating: 5,
  },
  {
    id: 6,
    name: 'Tanmay Gupta',
    course: 'Acoustic Guitar',
    quote: "I've been learning here for 6 months. The progress is visible. The staff is friendly and the studio is well maintained.",
    rating: 5,
  },
  {
    id: 7,
    name: 'Ishita Rawat',
    course: 'Vocal Student',
    quote: "Joining TCAM was the best decision for my musical journey. The personalized attention each student gets is commendable.",
    rating: 5,
  },
  {
    id: 8,
    name: 'Karthik Aryan',
    course: 'Guitar & Vocals',
    quote: "Great value for money. The quality of education is top-notch. Truly the best music academy in the city.",
    rating: 5,
  },
  {
    id: 9,
    name: 'Shreya Pandey',
    course: 'Ukulele Course',
    quote: "Such a fun and welcoming environment! I learned to play my favorite songs on the ukulele in just a few weeks.",
    rating: 5,
  },
  {
    id: 10,
    name: 'Amitabh Mishra',
    course: 'Piano Studies',
    quote: "Excellent faculty and great learning environment. My daughter loves her classes here. 5 stars all the way!",
    rating: 5,
  },
  {
    id: 11,
    name: 'Preeti Sharma',
    course: 'Beginner Guitar',
    quote: "I started from zero and now I can play several songs. The step-by-step teaching method is very effective.",
    rating: 5,
  },
  {
    id: 12,
    name: 'Vivek Oberoi',
    course: 'Intermediate Piano',
    quote: "The academy provides a very professional platform for aspiring musicians. Highly recommended for serious learners.",
    rating: 5,
  },
  {
    id: 13,
    name: 'Neha Kakkar',
    course: 'Voice Coaching',
    quote: "The best part about TCAM is the individual attention and the passion of the teachers. It's not just a class, it's an experience.",
    rating: 5,
  },
  {
    id: 14,
    name: 'Rajesh Khanna',
    course: 'Guitar Hobbyist',
    quote: "A perfect place to pursue your hobby. The batch timings are flexible and the location is very convenient.",
    rating: 5,
  },
  {
    id: 15,
    name: 'Sunita Williams',
    course: 'Piano & Theory',
    quote: "Very impressed with the technical knowledge of the staff. They make complex music theory easy to understand.",
    rating: 5,
  },
  {
    id: 16,
    name: 'Akash Verma',
    course: 'Lead Guitar',
    quote: "If you want to master the guitar, this is the only place in Lucknow you should consider. Pure excellence.",
    rating: 5,
  },
  {
    id: 17,
    name: 'Pooja Hegde',
    course: 'Vocal Performance',
    quote: "The confidence I've gained through their performance coaching is life-changing. Thank you TCAM!",
    rating: 5,
  },
  {
    id: 18,
    name: 'Manish Malhotra',
    course: 'Piano Student',
    quote: "Elegant studio, professional teachers, and a great vibe. It's a premium learning experience.",
    rating: 5,
  },
  {
    id: 19,
    name: 'Deepika Singh',
    course: 'Ukulele Beginner',
    quote: "Loved the teaching style. It's very interactive and student-friendly. Highly recommended for kids and adults alike.",
    rating: 5,
  },
  {
    id: 20,
    name: 'Ranveer Singh',
    course: 'Guitar Advanced',
    quote: "Top level training for advanced players as well. They really push you to achieve your potential.",
    rating: 5,
  }
];
